### PR TITLE
strip query string from url

### PR DESCRIPTION
**Pull request by ffflabs**
I've noticed that PHP Debugbar appends a query string in the form of a timestamp to bust caching. For example:

```
/_debugbar/resources/dump.js?_=1423534299676
```

and this will cause method `setAssetsRoute()` look for a file that doesn't exist:

``` php
 file_get_contents(/home/amenadiel/www/vendor/maximebf/debugbar/src/DebugBar/Resources/dump.js?_=1423534299676): failed to open stream: No such file or directory
```

this pull request just adds a conditional that would strip whatever comes after the file extension.

### CODE REVIEW

**Comment by yusukezzz** [comment]
sorry, my english is poor.

I can't reproduction this issue.
resource uri generate statically from \Slim\DebugBar.
PHP Debugbar really added query string? every request?

Please tell me more details in order to reproduction.
e.g. PHP Debugbar version in your app.

**Comment by ffflabs** [comment]
Slim 2.5.0, 
Debugbar 1.10.2
Slim-Debugbar 1.0.4

And no, it doesn't happen everytime. It seems it only happens as a result of ajax calls. The app loads a front-end made with Twig templates, then requests extra info to the backend through ajax calls. Most of them return only json, a few do return html. It seems these ajax calls generate debugbar urls with query string.

**Comment by yusukezzz** [comment]
Okay, Perhaps I was understanding.
This behavior I will reproduce by ajax request of jquery to receive the html content.
Resource uri not need when ajax response.

I'll try to fix.

**Comment by yusukezzz** [comment]
I solved this problem in the commit "272b4fd3a2".
slim-debugbar now support capturing and storing ajax request data.
Please check the dev-master.

**Comment by ffflabs** [comment]
cool, thanks

**Pull request closed without merging**
